#!/usr/bin/env python3
"""
generate_config.py

Simple Excel -> C header generator for vendor/device -> logical control mappings.

Expected input sheet with columns:
  vendor_id | device_id | logical_control | driver_symbol

This script emits `config_generated.h` and `config_generated.c` into the
components/common directory.
"""
import argparse
import os
import csv
from openpyxl import load_workbook

TEMPLATE_H = '''/* Auto-generated by generate_config.py - DO NOT EDIT */
#ifndef CONFIG_GENERATED_H
#define CONFIG_GENERATED_H

#include "device_registry.h"

#define CFG_VERSION "{cfg_version}"

extern const control_mapping_t VENDOR_DEVICE_MAPPINGS[];

#endif
'''

TEMPLATE_C = '''/* Auto-generated by generate_config.py - DO NOT EDIT */
#include "config_generated.h"

const control_mapping_t VENDOR_DEVICE_MAPPINGS[] = {{
{entries}
    {{ .control_id = CONTROL_INVALID, .driver = NULL }}
}};
'''

def parse_sheet(path, sheet_name=None):
    # Support .xlsx (Excel) and .csv inputs
    if path.lower().endswith('.csv'):
        out = []
        with open(path, newline='') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                # Normalize keys to lowercase
                rec = {k.strip().lower(): (v.strip() if isinstance(v, str) else v) for k, v in row.items()}
                out.append(rec)
        return out

    wb = load_workbook(path, data_only=True)
    if sheet_name:
        ws = wb[sheet_name]
    else:
        ws = wb.active
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return []
    # Normalize headers
    headers = [str(h).strip().lower() for h in rows[0]]
    out = []
    for r in rows[1:]:
        if not any(r):
            continue
        rec = dict(zip(headers, r))
        out.append(rec)
    return out

def make_entries(records):
    lines = []
    for rec in records:
        lc = rec.get('logical_control')
        driver = rec.get('driver_symbol')
        if not lc or not driver:
            continue
        lc_sym = 'CONTROL_' + str(lc).strip().upper()
        lines.append(f'    {{ .control_id = {lc_sym}, .driver = (driver_handle_t)&{driver} }},')
    return '\n'.join(lines)

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--input', '-i', required=True)
    p.add_argument('--sheet', '-s', default=None)
    p.add_argument('--out', '-o', default='components/common')
    p.add_argument('--cfg-version', default='CFG_2026_05_V1')
    args = p.parse_args()

    records = parse_sheet(args.input, args.sheet)
    entries = make_entries(records)
    h = TEMPLATE_H.format(cfg_version=args.cfg_version)
    c = TEMPLATE_C.format(entries=entries)

    out_h = os.path.join(args.out, 'config_generated.h')
    out_c = os.path.join(args.out, 'config_generated.c')
    with open(out_h, 'w', newline='\n') as fh:
        fh.write(h)
    with open(out_c, 'w', newline='\n') as fc:
        fc.write(c)
    print('Generated', out_h, out_c)

if __name__ == '__main__':
    main()
